import { AppData, Message, MessageReply } from "../types";
import { normalizeAppData } from "./localStore";
export const cloudModuleKeys = ["settings","bucketItems","periodRecords","messages","locations","travelCheckins","musicItems","mediaItems","foodPlaces","savingGoals","achievements","moments","comments","anniversaries"] as const;
export type CloudModuleKey = typeof cloudModuleKeys[number];
export type ListModuleKey = Exclude<CloudModuleKey, "settings">;
export type CloudStatus = "off" | "connecting" | "saving" | "saved" | "pending" | "error";
export type PendingOperation = { opId:string; clientId:string; module:CloudModuleKey; recordId:string; operation:"upsert-record"|"delete-record"|"set-setting"|"add-reply"|"delete-reply"; payload?:unknown; createdAt:string; localOnly?:boolean };
type CloudRow={id:string;data:unknown;updated_at:string}; type OperationCreator=(module:CloudModuleKey,recordId:string,operation:PendingOperation["operation"],payload?:unknown,localOnly?:boolean)=>void;
const pendingKey="couple-time-capsule-pending-ops"; const migrationKey="couple-time-capsule-sync-migration-v2"; const clientKey="couple-time-capsule-client-id";
export function canUseCloudSync(){return typeof window!=="undefined"&&typeof window.fetch==="function";}
export function cloudErrorMessage(error:unknown){const item=(error&&typeof error==="object"?error:{}) as {message?:string;code?:string;status?:number};const message=item.message??String(error??"");if(/failed to fetch|fetch failed|abort|network|网络/i.test(message))return"网络暂时无法连接云端，修改已保留并会自动重试";if(item.status===409||item.code==="CONFLICT")return"另一台设备刚刚修改了内容，正在合并重试";if(item.status===401||item.status===403||item.code==="42501")return"云端权限配置不完整，请检查 Netlify 环境变量和 Supabase 策略";if(item.status===404||item.code==="42P01")return"云端代理未部署或数据表不存在，请重新部署 Netlify";return message&&!/TypeError|Error/.test(message)?`云端保存失败：${message}`:"云端保存失败，正在自动重试";}
export function getClientId(){const existing=localStorage.getItem(clientKey);if(existing)return existing;const value=crypto.randomUUID();try{localStorage.setItem(clientKey,value);}catch{/* storage is optional */}return value;}
export function loadPendingOperations(){try{const parsed=JSON.parse(localStorage.getItem(pendingKey)||"[]");return Array.isArray(parsed)?parsed:[];}catch{return[];}}
export function compactPendingOperations(operations:PendingOperation[]){const result:PendingOperation[]=[];for(const operation of operations){const previous=result.findIndex((item)=>item.module===operation.module&&item.recordId===operation.recordId&&((item.operation==="upsert-record"&&operation.operation==="upsert-record")||(item.operation==="delete-record"&&operation.operation==="upsert-record")||(item.operation==="upsert-record"&&operation.operation==="delete-record")));if(previous>=0){const old=result[previous];if(old.operation==="upsert-record"&&operation.operation==="delete-record"&&old.localOnly)result.splice(previous,1);else if(operation.operation==="delete-record")result[previous]={...operation,localOnly:old.localOnly};else result[previous]={...operation,localOnly:old.localOnly??operation.localOnly};continue;}if((operation.operation==="add-reply"||operation.operation==="delete-reply")&&operation.module==="messages"){const replyId=operation.operation==="add-reply"?(operation.payload as MessageReply)?.id:String(operation.payload??"");const match=result.findIndex((item)=>item.module==="messages"&&item.recordId===operation.recordId&&(item.operation==="add-reply"||item.operation==="delete-reply")&&(item.operation==="add-reply"?(item.payload as MessageReply)?.id:String(item.payload??""))===replyId);if(match>=0){result.splice(match,1);if(operation.operation==="add-reply")result.push(operation);continue;}}result.push(operation);}return result;}
export function savePendingOperations(operations:PendingOperation[]){const compacted=compactPendingOperations(operations);const serialized=JSON.stringify(compacted);try{localStorage.setItem(pendingKey,serialized);}catch(error){if(!(error instanceof DOMException)||error.name!=="QuotaExceededError")throw error;localStorage.removeItem("couple-time-capsule-data");localStorage.setItem(pendingKey,serialized);}}
export function diffAppData(previous:AppData,next:AppData,clientId:string){const operations:PendingOperation[]=[];const create=(module:CloudModuleKey,recordId:string,operation:PendingOperation["operation"],payload?:unknown,localOnly?:boolean)=>operations.push({opId:crypto.randomUUID(),clientId,module,recordId,operation,payload,createdAt:new Date().toISOString(),localOnly});if(previous.startDate!==next.startDate)create("settings","startDate","set-setting",next.startDate);for(const module of cloudModuleKeys){if(module==="settings"||module==="messages")continue;diffRecords(previous[module],next[module],module,create);}diffMessages(previous.messages,next.messages,create);return operations;}
function diffRecords(previous:Array<{id:string}>,next:Array<{id:string}>,module:ListModuleKey,create:OperationCreator){const previousMap=new Map(previous.map((r)=>[r.id,r]));const nextMap=new Map(next.map((r)=>[r.id,r]));for(const record of next){const old=previousMap.get(record.id);if(!old)create(module,record.id,"upsert-record",record,true);else if(JSON.stringify(old)!==JSON.stringify(record))create(module,record.id,"upsert-record",record);}for(const record of previous)if(!nextMap.has(record.id))create(module,record.id,"delete-record");}
function diffMessages(previous:Message[],next:Message[],create:OperationCreator){const previousMap=new Map(previous.map((r)=>[r.id,r]));const nextMap=new Map(next.map((r)=>[r.id,r]));for(const message of next){const old=previousMap.get(message.id);if(!old){create("messages",message.id,"upsert-record",message,true);continue;}const {replies:oldReplies=[],...oldBase}=old;const {replies:nextReplies=[],...nextBase}=message;if(JSON.stringify(oldBase)!==JSON.stringify(nextBase))create("messages",message.id,"upsert-record",nextBase);const oldMap=new Map(oldReplies.map((r)=>[r.id,r]));const nextMapReplies=new Map(nextReplies.map((r)=>[r.id,r]));for(const reply of nextReplies){const oldReply=oldMap.get(reply.id);if(!oldReply||JSON.stringify(oldReply)!==JSON.stringify(reply))create("messages",message.id,"add-reply",reply);}for(const reply of oldReplies)if(!nextMapReplies.has(reply.id))create("messages",message.id,"delete-reply",reply.id);}for(const message of previous)if(!nextMap.has(message.id))create("messages",message.id,"delete-record");}
export function applyOperations(data:AppData,operations:PendingOperation[]){let next=structuredClone(data);for(const operation of operations)next=applyOperation(next,operation);return normalizeAppData(next);}
function applyOperation(data:AppData,operation:PendingOperation){if(operation.module==="settings")return{...data,startDate:String(operation.payload??"")};const records=[...data[operation.module]] as Array<{id:string}>;const index=records.findIndex((r)=>r.id===operation.recordId);if(operation.operation==="delete-record"){if(index>=0)records.splice(index,1);}else if(operation.operation==="upsert-record"){const incoming=operation.payload as {id:string};if(index>=0&&operation.module==="messages"){const existing=records[index] as Message;const updated=incoming as Message;records[index]={...existing,...updated,replies:mergeReplies(existing.replies??[],updated.replies??[])} as {id:string};}else if(index>=0)records[index]=incoming;else records.unshift(incoming);}else if(operation.module==="messages"&&index>=0){const message={...(records[index] as Message)};if(operation.operation==="add-reply"){message.replies=mergeReplies(message.replies??[],[operation.payload as MessageReply]);message.status="replied";}else if(operation.operation==="delete-reply"){message.replies=(message.replies??[]).filter((r)=>r.id!==operation.payload);}records[index]=message;}return{...data,[operation.module]:records} as AppData;}
function mergeReplies(remote:MessageReply[],local:MessageReply[]){const map=new Map(remote.map((r)=>[r.id,r]));local.forEach((r)=>map.set(r.id,r));return[...map.values()];}
async function request(path:string,init:RequestInit={}){const response=await fetch(path,{...init,headers:{"content-type":"application/json",...(init.headers||{})}});let body:unknown=null;try{body=await response.json();}catch{/* response may be empty */}if(!response.ok){const error=Object.assign(new Error((body as {message?:string})?.message||`代理请求失败（${response.status}）`),{status:response.status,code:(body as {code?:string})?.code});throw error;}return body;}
async function fetchRows(){const rows=await request("/api/cloud-state?ids="+cloudModuleKeys.join(","));return new Map((rows as CloudRow[]).map((row)=>[row.id,row]));}
async function putModule(module:CloudModuleKey,data:AppData,expectedUpdatedAt=""){return request("/api/cloud-state",{method:"PUT",body:JSON.stringify({id:module,data:moduleValue(data,module),expectedUpdatedAt})}) as Promise<CloudRow>;}
function emptyData():AppData{return{startDate:"",bucketItems:[],periodRecords:[],messages:[],locations:[],travelCheckins:[],musicItems:[],mediaItems:[],foodPlaces:[],savingGoals:[],achievements:[],moments:[],comments:[],anniversaries:[]};}
function dataFromRows(rows:Map<string,CloudRow>,fallback:AppData){const data=structuredClone(fallback);for(const module of cloudModuleKeys){const row=rows.get(module);if(!row)continue;if(module==="settings")data.startDate=String((row.data as {startDate?:string})?.startDate??"");else data[module]=(Array.isArray(row.data)?row.data:[]) as never;}return normalizeAppData(data);}
function moduleValue(data:AppData,module:CloudModuleKey){return module==="settings"?{startDate:data.startDate}:data[module];}
function moduleIntoData(module:CloudModuleKey,value:unknown){const data=emptyData();if(module==="settings")data.startDate=String((value as {startDate?:string})?.startDate??"");else data[module]=(Array.isArray(value)?value:[]) as never;return data;}
export async function initializeCloudData(localData:AppData){const rows=await fetchRows();const legacy=rows.get("default");let remote=rows.size>1?dataFromRows(rows,normalizeAppData(legacy?.data??localData)):normalizeAppData(legacy?.data??localData);if(rows.size<=1){for(const module of cloudModuleKeys){try{await putModule(module,remote);}catch(error){if((error as {status?:number}).status!==409)throw error;}}}else{for(const module of cloudModuleKeys)if(!rows.has(module))await putModule(module,remote);}if(localStorage.getItem(migrationKey)!=="done"){remote=mergeRecoveryData(remote,localData);for(const module of cloudModuleKeys)await putModule(module,remote);try{localStorage.setItem(migrationKey,"done");}catch{/* migration marker is optional */}}return remote;}
export async function readCloudData(){const rows=await fetchRows();return rows.size>0?dataFromRows(rows,emptyData()):null;}
export async function flushPendingOperations(operations:PendingOperation[]){if(operations.length===0)return;const grouped=new Map<CloudModuleKey,PendingOperation[]>();for(const op of compactPendingOperations(operations))grouped.set(op.module,[...(grouped.get(op.module)??[]),op]);for(const [module,ops] of grouped)await flushModule(module,ops);}
async function flushModule(module:CloudModuleKey,operations:PendingOperation[]){for(let attempt=0;attempt<6;attempt++){const rows=await fetchRows();const row=rows.get(module);const base=row?moduleIntoData(module,row.data):emptyData();const updated=applyOperations(base,operations);try{await putModule(module,updated,row?.updated_at??"");return;}catch(error){if((error as {status?:number}).status!==409&&attempt===5)throw error;await new Promise((resolve)=>window.setTimeout(resolve,180*(attempt+1)));}}throw new Error("云端数据正在被另一台设备更新，请稍后重试");}
function mergeRecoveryData(remote:AppData,local:AppData){const merged=structuredClone(remote);for(const module of cloudModuleKeys){if(module==="settings")continue;const records=new Map((merged[module] as Array<{id:string}>).map((r)=>[r.id,r]));for(const localRecord of local[module] as Array<{id:string}>){const remoteRecord=records.get(localRecord.id);if(!remoteRecord)records.set(localRecord.id,localRecord);else if(module==="messages"){const remoteMessage=remoteRecord as Message;const localMessage=localRecord as Message;records.set(localRecord.id,{...remoteMessage,replies:mergeReplies(remoteMessage.replies??[],localMessage.replies??[])} as {id:string});}}merged[module]=[...records.values()] as never;}if(!merged.startDate&&local.startDate)merged.startDate=local.startDate;return normalizeAppData(merged);}
export function subscribeCloudChanges(onChange?: () => void){void onChange;return null;}
export function removeSharedSubscription(channel?: unknown){void channel;return undefined;}
