const modules = new Set(["settings", "bucketItems", "periodRecords", "messages", "locations", "travelCheckins", "musicItems", "mediaItems", "foodPlaces", "savingGoals", "achievements", "moments", "comments", "anniversaries"]);
const table = "shared_app_state";
function json(statusCode, body) { return { statusCode, headers: { "content-type": "application/json; charset=utf-8", "cache-control": "no-store" }, body: JSON.stringify(body) }; }
function config() { const url = process.env.SUPABASE_URL; const key = process.env.SUPABASE_ANON_KEY; if (!url || !key) throw new Error("Netlify 环境变量未配置"); return { url: url.endsWith("/") ? url.slice(0, -1) : url, key }; }
async function supabaseRequest(path, init = {}) { const { url, key } = config(); const response = await fetch(`${url}/rest/v1/${path}`, { ...init, headers: { apikey: key, authorization: `Bearer ${key}`, "content-type": "application/json", ...(init.headers || {}) } }); const text = await response.text(); let data = null; try { data = text ? JSON.parse(text) : null; } catch { data = text; } if (!response.ok) { const error = new Error(data && data.message ? data.message : `Supabase 请求失败（${response.status}）`); error.status = response.status; throw error; } return data; }
export async function handler(event) {
  try {
    if (event.httpMethod === "GET") { const requested = new URL(event.rawUrl || "http://localhost/?" + (event.rawQuery || "")).searchParams.get("ids"); const ids = requested ? requested.split(",").filter((id) => id === "default" || modules.has(id)) : [...modules, "default"]; const filter = `id=in.(${ids.join(",")})`; const rows = await supabaseRequest(`${table}?select=id,data,updated_at&${filter}`); return json(200, rows); }
    if (event.httpMethod !== "PUT") return json(405, { message: "只支持 GET 和 PUT" });
    const body = JSON.parse(event.body || "{}"); const id = String(body.id || ""); if (!modules.has(id)) return json(400, { message: "不允许写入这个模块" }); if (!body.data || typeof body.data !== "object") return json(400, { message: "数据格式不正确" }); const expected = body.expectedUpdatedAt ? String(body.expectedUpdatedAt) : ""; const now = new Date().toISOString();
    if (!expected) { try { const inserted = await supabaseRequest(table, { method: "POST", headers: { prefer: "return=representation" }, body: JSON.stringify({ id, data: body.data, updated_at: now }) }); return json(200, Array.isArray(inserted) ? inserted[0] : inserted); } catch (error) { if (error.status === 409) return json(409, { message: "云端模块已经存在", code: "CONFLICT" }); throw error; } }
    const updated = await supabaseRequest(`${table}?id=eq.${encodeURIComponent(id)}&updated_at=eq.${encodeURIComponent(expected)}`, { method: "PATCH", headers: { prefer: "return=representation" }, body: JSON.stringify({ data: body.data, updated_at: now }) }); if (!Array.isArray(updated) || updated.length === 0) return json(409, { message: "云端数据已被另一台设备更新", code: "CONFLICT" }); return json(200, updated[0]);
  } catch (error) { return json(Number(error && error.status) || 502, { message: error instanceof Error ? error.message : "云端代理请求失败" }); }
}
